language: java

sudo: required

services:
  - docker

before_install:
  - docker ps -aq -f status=exited
  - docker build -t mikkel/green .


script:
  - docker run mikkel/green /bin/sh -c "ant; ant test"
