sudo: required

language: java

services:
  - docker



#script:
# - ant;
# - ant test;

before_install:
  -docker build -t mikkkeldp/green .

script:
  - docker run mikkkeldp/green /bin/sh -c "ant; ant test"
